[package]
name = "c-lang"
version = "0.1.3"
edition = "2021"
description = "Scripting language made in rust"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyu_rust_util = "0.1.66"
